// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SVGLClub.Data;

#nullable disable

namespace SVGLClub.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250527185719_SessionDataRemoveOldStructure")]
    partial class SessionDataRemoveOldStructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SVGLClub.Data.AssettoSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationSecs")
                        .HasColumnType("int");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RaceLaps")
                        .HasColumnType("int");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrackConfig")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrackName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("SVGLClub.Data.SessionCar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssettoSessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssettoSessionId");

                    b.ToTable("SessionCars");
                });

            modelBuilder.Entity("SVGLClub.Data.SessionEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssettoSessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssettoSessionId");

                    b.ToTable("SessionEvents");
                });

            modelBuilder.Entity("SVGLClub.Data.SessionLap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssettoSessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssettoSessionId");

                    b.ToTable("SessionLaps");
                });

            modelBuilder.Entity("SVGLClub.Data.SessionResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssettoSessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssettoSessionId");

                    b.ToTable("SessionResult");
                });

            modelBuilder.Entity("SVGLClub.Data.SessionCar", b =>
                {
                    b.HasOne("SVGLClub.Data.AssettoSession", null)
                        .WithMany("Cars")
                        .HasForeignKey("AssettoSessionId");
                });

            modelBuilder.Entity("SVGLClub.Data.SessionEvent", b =>
                {
                    b.HasOne("SVGLClub.Data.AssettoSession", null)
                        .WithMany("Events")
                        .HasForeignKey("AssettoSessionId");
                });

            modelBuilder.Entity("SVGLClub.Data.SessionLap", b =>
                {
                    b.HasOne("SVGLClub.Data.AssettoSession", null)
                        .WithMany("Laps")
                        .HasForeignKey("AssettoSessionId");
                });

            modelBuilder.Entity("SVGLClub.Data.SessionResult", b =>
                {
                    b.HasOne("SVGLClub.Data.AssettoSession", null)
                        .WithMany("Results")
                        .HasForeignKey("AssettoSessionId");
                });

            modelBuilder.Entity("SVGLClub.Data.AssettoSession", b =>
                {
                    b.Navigation("Cars");

                    b.Navigation("Events");

                    b.Navigation("Laps");

                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
